name: Checking Tests

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"

      - name: Install dependencies
        run: npm run install

      - name: Build project
        run: npm run build

      - name: Debug event
        run: echo "${{ toJson(github.event) }}"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test-gui
        env:
          CYPRESS_BASE_URL: "http://localhost:3000"
