name: Checking Tests

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"

      - name: Clean and Install root dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Clean and Install client dependencies
        run: |
          cd client
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm install @rollup/rollup-linux-x64-gnu

      - name: Clean and Install server dependencies
        run: |
          cd server
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Build project
        run: npm run render-build

      - name: Run Vitest tests
        run: npm run test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run develop
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_BASE_URL: "http://localhost:3000"
