name: Checking Tests

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"

      - name: Install dependencies
        run: |
          cd ./Develop
          npm install --include=dev

      - name: Build project
        run: |
          cd ./Develop
          npm run build

      - name: Start the application
        run: |
          cd ./Develop
          npm run develop &
        env:
          NODE_ENV: test

      - name: Wait for the server to be ready
        run: |
          timeout 60s bash -c 'until curl -s http://localhost:3001; do sleep 5; done'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
          wait-on: "http://localhost:3001"
          browser: electron
        env:
          CYPRESS_BASE_URL: "http://localhost:3001"
