name: Checking Tests

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"

      - name: Clean and Install root dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Clean and Install client dependencies
        run: |
          cd client
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm install @rollup/rollup-linux-x64-gnu

      - name: Clean and Install server dependencies
        run: |
          cd server
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Build project
        run: npm run render-build

      - name: Start backend server
        run: |
          cd server
          npm run start &
        env:
          NODE_ENV: test
          MONGODB_URI: "mongodb://localhost:27017/techquiz"

      - name: Wait for backend server to start
        run: |
          timeout 60s bash -c 'until curl -s http://localhost:3001; do sleep 5; done'
          echo "Backend server is running!"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test-component
          wait-on: "http://localhost:3000"
          wait-on-timeout: 90
        env:
          CYPRESS_BASE_URL: "http://localhost:3000"
